version: '3'
services:
  db:
    image: mysql
    environment: 
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
  db-admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 127.0.0.1:8888:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/var/www/html:ro
      - ./cert:/etc/nginx/ssl:ro
    
    
    



